version: '3'

services:
  web:
   image: 'audax_v1.0-php'
   ports: 
   - '8000:8000'
   volumes: 
   - ./:/app
   command: php artisan serve --host=0.0.0.0
   links:
   - "mysql"

  mysql:
    image: 'mysql:8.0'
    ports:
    - '3306:3306'
    environment:
    - MYSQL_ROOT_PASSWORD=d4v1d001
    volumes:
    - mysql-data:/var/lib/mysql
volumes:
  mysql-data: